name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: '🚀 Features'
    label: 'Feature'
  - title: '🐛 Bug Fixes'
    label: 'Bug'
  - title: '🧰 Maintenance'
    label: 'Maintenance'
  - title: '📖 Documentation'
    label: 'Docs'
change-template: '- (#$NUMBER) $TITLE - Thanks to @$AUTHOR '